name: Convert Markdown to ICML

on:
  workflow_dispatch:

jobs:
  convert_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Download Pandoc
        env:
          VER: "3.6.2"
          CHECKSUM: "50efac0830633f47c775beab6178dabb38ecb44a05353b27c52716a48bdcb578"
        run: |-
          curl -L "https://github.com/jgm/pandoc/releases/download/$VER/pandoc-$VER-linux-amd64.tar.gz" | tar -xz --strip-components=2 -C . "pandoc-$VER/bin/pandoc"
          echo "$CHECKSUM  pandoc" | sha256sum -c
      - name: Convert Markdown to ICML
        run: .github/pandoc.sh
      - name: Fixup ICML with Cheerio
        run: |-
          npm --prefix .github/node-fixup-icml install
          node .github/node-fixup-icml/index.js
      - name: Commit and push if changed
        run: |-
          cd content-indesign
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          commit=$(git rev-parse --short "$GITHUB_SHA")
          git commit -m "Latest data: $timestamp (from commit $commit)" || exit 0
          git push
